server:
  address: "127.0.0.1"
  port: 3001
  public_url: "https://smee.io/9U5ob2Y9V5u8iulx"

github:
  v3_api_url: "https://api.github.com/"
  app:
    integration_id: 104202
    webhook_secret: "atKnrwDawOa"
    private_key: |SHA256:0oksi0MkP2l92kuJAYudv3iKNLsCA5Yy7k8q8L+oz2A=
      

app_configuration:
  pull_request_preamble: "I am jack bot."
  project_id: #Add the project number here (ex: https://github.com/orgs/ncr-swt-retail/projects/1 you'd put 1 here)
  epic_preamble: "\n<!-- JACKBOT -->\n___\n### Issues\n<!-- LIST -->\n"
  epic_postamble: "\n<!-- ENDLIST -->\n To add an issue to this list use 
  the command `/issue #{issue_number}` in the comments of an issue.\n[Click here to find out 
  more about jackbot](https://github.com/apps/ncr-jack-bot)\n___\n<!-- ENDJACKBOT -->\n"
  issue_preamble: "\n<!-- JACKBOT -->\n___\n### Linked Epics\n<!-- LIST -->\n"
  issue_postamble: "\n<!-- ENDLIST -->\n Add this issue to another epic by using 
  the `/epic #{epic_number}` command in the comments here.\n[Click here to find out more 
  about jackbot](https://github.com/apps/ncr-jack-bot)\n___\n<!-- ENDJACKBOT -->\n"
